package tetris

class MovementTests extends TetrisTestSuiteBase {

  test("testMovement") {
    checkGame( List(TestFrame(4,
      """..SS..
        |.SS...
        |......
        |......"""),
      TestFrame(4, List(Left),
        """.SS...
          |SS....
          |......
          |......"""),
      TestFrame(4, List(Right),
        """..SS..
          |.SS...
          |......
          |......"""),
      TestFrame(4, List(Right),
        """...SS.
          |..SS..
          |......
          |......"""),
      TestFrame(4, List(Right),
        """....SS
          |...SS.
          |......
          |......"""),
      TestFrame(4, List(Down),
        """......
          |....SS
          |...SS.
          |......"""),
      TestFrame(4, List(Left),
        """......
          |...SS.
          |..SS..
          |......"""),
      TestFrame(4, List(Left),
        """......
          |..SS..
          |.SS...
          |......"""),
      TestFrame(4, List(Left),
        """......
          |.SS...
          |SS....
          |......"""),
      TestFrame(4, List(Down),
        """......
          |......
          |.SS...
          |SS...."""),
      TestFrame(4, List(Right),
        """......
          |......
          |..SS..
          |.SS..."""),
      TestFrame(4, List(Right),
        """......
          |......
          |...SS.
          |..SS.."""),
      TestFrame(4, List(Right),
        """......
          |......
          |....SS
          |...SS."""))
    ,hint = "Moving left, right and down should work as expected")
  }

  test("testMovement2") {
    checkGame( List(TestFrame(5,
      """...T...
        |..TTT..
        |.......
        |......."""),
      TestFrame(5, List(Left),
        """..T....
          |.TTT...
          |.......
          |......."""),
      TestFrame(5, List(Left),
        """.T.....
          |TTT....
          |.......
          |......."""),
      TestFrame(5, List(Down),
        """.......
          |.T.....
          |TTT....
          |......."""),
      TestFrame(5, List(Right),
        """.......
          |..T....
          |.TTT...
          |......."""),
      TestFrame(5, List(Right),
        """.......
          |...T...
          |..TTT..
          |......."""),
      TestFrame(5, List(Right),
        """.......
          |....T..
          |...TTT.
          |......."""),
      TestFrame(5, List(Right),
        """.......
          |.....T.
          |....TTT
          |......."""),
      TestFrame(5, List(Down),
        """.......
          |.......
          |.....T.
          |....TTT"""),
      TestFrame(5, List(Left),
        """.......
          |.......
          |....T..
          |...TTT."""),
      TestFrame(5, List(Left),
        """.......
          |.......
          |...T...
          |..TTT.."""),
      TestFrame(5, List(Left),
        """.......
          |.......
          |..T....
          |.TTT..."""),
      TestFrame(5, List(Left),
        """.......
          |.......
          |.T.....
          |TTT...."""))
      ,hint = "Moving left, right and down should work as expected")
  }

}
