package tetris

class SpawnTests extends TetrisTestSuiteBase {

  test("testSpawn") {
    checkGame(List(TestFrame(0,
      """.....
        |.IIII
        |.....
        |....."""),
      TestFrame(0, List(Down),
        """.....
          |.....
          |.IIII
          |....."""),
      TestFrame(0, List(Down),
        """.....
          |.....
          |.....
          |.IIII"""),
      TestFrame(0, List(Down),
        """.....
          |.IIII
          |.....
          |.IIII"""),
      TestFrame(0, List(Down),
        """.....
          |.....
          |.IIII
          |.IIII"""),
      TestFrame(0, List(Down),
        """.....
          |.IIII
          |.IIII
          |.IIII""")),
    hint ="A new tetromino is spawned when moveDown is called but the current tetromino cannot move down.")
  }


  test("testSpawn2") {
    checkGame( List(TestFrame(1,
      """J...
        |JJJ.
        |....
        |....
        |....
        |...."""),
      TestFrame(1, List(Down),
        """....
          |J...
          |JJJ.
          |....
          |....
          |...."""),
      TestFrame(1, List(Down),
        """....
          |....
          |J...
          |JJJ.
          |....
          |...."""),
      TestFrame(1, List(Down),
        """....
          |....
          |....
          |J...
          |JJJ.
          |...."""),
      TestFrame(1, List(Down),
        """....
          |....
          |....
          |....
          |J...
          |JJJ."""),
      TestFrame(2, List(Down),
        """..L.
          |LLL.
          |....
          |....
          |J...
          |JJJ."""),
      TestFrame(2, List(Down),
        """....
          |..L.
          |LLL.
          |....
          |J...
          |JJJ."""),
      TestFrame(2, List(Down),
        """....
          |....
          |..L.
          |LLL.
          |J...
          |JJJ."""),
      TestFrame(3, List(Down),
        """.OO.
          |.OO.
          |..L.
          |LLL.
          |J...
          |JJJ.""")),
      hint ="A new tetromino is spawned when moveDown is called but the current tetromino cannot move down.")
  }
}
